netflix_project/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home)
    
]

netflix_project/netflix_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('signin/', include('signin.urls')),
    path('signup/',include('signin.urls'))
    
]

netflix_project/signin/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'signin'
urlpatterns = [
    path("signin/",views.signin,name='signin_page'),
    path('signup/',views.signup,name='signup_page')
    
]

netflix_project/home/models.py
from django.db import models

# Create your models here.

netflix_project/signin/models.py
from django.db import models

# Create your models here.

netflix_project/home/views.py
from django.shortcuts import render


# Create your views here.


def home(request):
    return render(request, 'home_templates/netflix.html')

netflix_project/signin/views.py
from django.shortcuts import render

# Create your views here.

def signin(request):
    return render(request,'signin_templates/signin.html')


def signup(request):
    return render(request,'signin_templates/signup_page.html')

netflix_project/home/templates/home_templates/netflix.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'home_static/css/netflix.css' %}">

</head>

<body>
    <div class="navbar">
        <div class="topleft">
            <img class="img" src="{% static 'home_static/images/Netflix-logo-red-black-png-768x436.png' %}" alt="">
        </div>

        <div class="options">
            <a href="">Home</a>
            <a href="">TV Shows</a>
            <a href="">Movies</a>
        </div>

        <div class="topright">
            <i style="font-size:24px" class="fa fa-search"></i>
            <i style="font-size:24px" class="fa">&#xf0f3;</i>
            <a href="{% url 'signin:signin_page' %}"><i style="font-size:24px" class="fa">&#xf2be;</i></a><br>
            <p style="text-align: right;">(this profile buttton works)</p>
        </div>
    </div>

    <div style="background-image: url('{% static 'home_static/images/the circle.png' %}');" class="backgroundimg">
        <div class="titles">
            <br><br><br>
            <h4>New Episodes coming on Wednesday<h4>
            <p>status and strategy collide in this social experiment and competition show where online players
                        flirt,befriend</p>
            <div class="buttons">
                <input class="play" type="button" value="Play">
                <input class="moreinfo" type="button" value="More Info">
            </div>

        </div>

    </div>


    <h3>Popular on Netflix</h3>
    <div class="row1">
        <div class="1"><img style="width:100%;" src="{% static 'home_static/images/wednesday-netflix-review.jpg' %}" alt=""></div>
        <div class="2"><img style="width:100%;" src="{% static 'home_static/images/friends.jpg' %}" alt=""></div>
        <div class="3"><img style="width:100%;" src="{% static 'home_static/images/moneyhiest.jpg' %}" alt=""></div>
    </div>

    <h3>Trending Now</h3>
    <div class="row1">
        <div class="1"><img style="width:100%;" src="{% static 'home_static/images/mismatch.jpg' %}" alt=""></div>
        <div class="2"><img style="width:100%;" src="{% static 'home_static/images/squidgame.jpg' %}" alt=""></div>
        <div class="3"><img style="width:100%;" src="{% static 'home_static/images/strangerthings.jpg' %}" alt=""></div>
    </div>

    <h3>Movies set in India</h3>
    <div class="row1">
        <div class="1"><img style="width:100%;" src="{% static 'home_static/images/gattakusthi.jpg' %}" alt=""></div>
        <div class="1"><img style="width:100%;" src="{% static 'home_static/images/gattakusthi.jpg' %}" alt=""></div>
        <!-- <div class="1"><img style="width:100%;" src="{% static 'home_static/images/gattakusthi.jpg' %}" alt=""></div> -->

        <!-- <div class="2"><img style="width:100%;" src="{% static 'home_static/images/major.jpg' %}" alt=""></div> -->
        <div class="3"><img style="width:110%;" src="{% static 'home_static/images/gunjan.jpg' %}" alt=""></div>
    </div>



</body>

</html>

netflix_project/signin/templates/signin_templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sing In</title>
    <link rel="stylesheet" href="{% static 'signin_static\css\signin.css' %}">
</head>

<body style="background-image: url( '{% static 'signin_static/images/grid.jpg' %}' );">
    <div class="logo">
        <img class="img" src="{% static 'signin_static\images\logo.png' %}" alt="">
    </div>

    <div class="form_box">
        <div class="forms">
            <div class="header">
                <h1>Sign In</h1>
            </div>
            <div class="inputs">
                <input type="text" placeholder="Email or phone number">
                <input type="password" placeholder="Password">
                <div class="btn">
                    <input type="button" value="Sign In">
                </div>
                <div class="signup">
                    <p>New to netflix?</p>
                    <a href="{% url 'signin:signup_page' %}">Sign up now</a>
                </div>
            </div>
    </div>
    </div>
</body>

</html>

netflix_project/signin/templates/signin_templates/signup_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'signin_static\css\signup.css' %}">
</head>

<body style="background-image: url( '{% static 'signin_static/images/grid.jpg' %}' );">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@600&family=Rubik+80s+Fade&display=swap');

        body {
            margin: 0px;
            padding: 0px;
        }
        .background{
            background-color: rgba(0, 0, 0, 0.603);
            height: 100%;
        }

        .logo img {
            width: 200px;
        }
        .content_box{
            display: flex;
            justify-content: center;
            align-items: center;
            padding-bottom: 390px;

        }

        .contents {
            font-size: x-large;
            text-align: center;
            font-family: 'Poppins', sans-serif;
            color: white;
        }

        .forms{
            /* display: grid;
            grid-template-columns: auto; */
            display: flex;
            justify-content: center;
        }

        .forms input{
            width: 500px;
            height: 50px;
            text-decoration: none;
            font-family: 'Poppins', sans-serif;
            margin: 20px;
        }
        .button{
            width: 100px;
            align-items: center;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-left: 400px;

        }

        .btn{
            background-color: rgb(191, 15, 15);
            font-family: 'Poppins', sans-serif;
            width: 110px;
            text-decoration: none;
            border: none;
            height: 50px;
            padding: 10px;
            
        }
    </style>


    <div class="background">
        <div class="logo">
            <img class="img" src="{% static 'signin_static\images\logo.png' %}" alt="">
        </div>
        <div class="content_box">
            <div class="contents">
                <h1>
                    Unlimited movies, TV shows and more.
                </h1>
                <h3>
                    Watch anywhere. Cancel anytime.
                </h3>
                <h5>
                    Ready to watch? Enter your email to create or restart your membership
                </h5>
               <div class="forms">
                <input type="email" placeholder="Email address">
               </div>
               <div class="button">
                <button class="btn">Get Started > </button>
               </div>
            </div>
        </div>
    </div>

</body>

</html>